### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by karthik340** [Callum-A/cosmwasm-zero-to-hero#2]
environment : mac air m1
replaced with docker run --rm -v "$(pwd)":/code \
  --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target \
  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
  cosmwasm/rust-optimizer-arm64:0.12.4 in script .
when i run ./scripts/deploy_local.sh i get an error saying 

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

Error: validator is not a valid name or address: decoding bech32 failed: invalid separator index -1

Error: rpc error: code = NotFound desc = rpc error: code = NotFound desc = account juno1lrt8qk7sefum8vkjdevj0pnwhw4jzs8w47244j not found: key not found
Usage:
  junod tx wasm store [wasm file] [flags]
Config Variables 

NEXT_PUBLIC_CW_STARTER_CODE_ID=
NEXT_PUBLIC_CW_STARTER_ADDRESS=
1

provided some parts of logs here

**Comment by Callum-A** [comment]
ah M1 chip, will look into it. Cheers for the issue.
