### ISSUE TITLE
error: failed to run custom build command for `openssl-sys v0.9.73`

### ISSUE THREAD

**Issue by alpereira7** [Callum-A/cosmwasm-zero-to-hero#3]
Hello.
I'm following the part Two of the tutorial, while installing the Environment Setup.
I execute this command
`cargo install cargo-generate --features vendored-openssl`
it compiles some libraries for a while, then ends with 
    `error: failed to run custom build command for `openssl-sys v0.9.73``

**Comment by Callum-A** [comment]
Interesting what OS are you using any more background on the issue?

**Comment by apereiraelno** [comment]
Hi @Callum-A thanks for your answer.
My OS is Windows 10.
I don't have much background, I just wanted to learn the tutorial and followed the IntelliJ IDEA installation according to Part 2 (Environment Setup).

Then **Ensuring Rustup is Installed**: OK

**Adding the WASM Target**: OK

Finally **Installing Cargo Generate** doesn't work.

I will add screenshot of the full error messages when I'm home.

**Comment by alpereira7** [comment]
Hi @Callum-A thanks for your answer.
My OS is Windows 10.
I don't have much background, I just wanted to learn the tutorial and followed the IntelliJ IDEA installation according to Part 2 (Environment Setup).

Then Ensuring Rustup is Installed: OK

Adding the WASM Target: OK

Finally Installing Cargo Generate doesn't work.

I will add screenshot of the full error messages when I'm home.

**Comment by Callum-A** [comment]
I'd recommend setting up WSL and Ubunutu as Windows is often awkward for CW dev
