### ISSUE TITLE
cw-template with branch clean-1.0-beta doesn't exist

### ISSUE THREAD

**Issue by taitruong** [Callum-A/cosmwasm-zero-to-hero#9]
https://github.com/Callum-A/cosmwasm-zero-to-hero/blob/83333b1c9388c583c6de9d18b88d86246aa693b4/02%20-%20Environment%20Setup/README.md?plain=1#L61

These branches can be used: 1.0-minimal or 1.0

**Comment by taitruong** [comment]
There is a also a tag "1.0-beta6". But it seems it can't be used:

> $ cargo generate --git https://github.com/CosmWasm/cw-template.git --branch 1.0-beta6 --name cw-starter
> Error: Please check if the Git user / repository exists.
>
> Caused by:
>     reference 'refs/remotes/origin/1.0-beta6' not found; class=Reference (4); code=NotFound (-3)

**Comment by Callum-A** [comment]
Have now updated it, use 1.0-minimal

**Comment by taitruong** [comment]
Thanks, also working on it, using 1.0-minimal and works fine. Great tutorial by the way, ser!
